spring.application.name=foodiesapi
server.port=8081
#mongodb configuration
spring.mongodb.uri = mongodb://localhost:27017/foodies

#AWS S3 configuration
aws.access.key = ${AWS_ACCESS_KEY}
aws.secret.key = ${AWS_SECRET_KEY}
aws.region.key = eu-north-1
aws.s3.bucketname = foodies-food-dinukas

jwt.secret.key  = 4c8f1c2f7c6a4d90f6e8c1a7b9d3e4f2a5c6b7d8e9f1a2c3d4e5f6a7b8c9d0e1
